### PR TITLE
Updated Multilingual support 

### PR DESCRIPTION
**Pull request by mvietri**
Add new codes for `lang` parameter. See https://openweathermap.org/current#multi for more details.

Closes https://github.com/vb2ae/OpenWeatherMap.Standard/issues/4

### CODE REVIEW

**Comment by mvietri** [comment]
Please, squash this PR. Using the built in editor here was kind of nightmare with spaces and tabs.

**Review by vb2ae — CHANGES_REQUESTED** [review]
The code you did looks good.  Could you update the Version, FileVersion, PackageVersion, and assembly version to 2.1.0 in the OpenWeatherMap.Standard project?

**Comment by mvietri** [comment]
> The code you did looks good. Could you update the Version, FileVersion, PackageVersion, and assembly version to 2.1.0 in the OpenWeatherMap.Standard project?

Sure. Do you want that changes in this PR or create another one just for the release?

**Comment by vb2ae** [comment]
Sorry I created it in another pr.   Thanks for your help

**Pull request merged**
